{
  "hash": "0ca1798a0167f05e87e97461eae93c6b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 13: Multilevel Models II\"\ndate: April 29, 2026\n---\n\n## Example Data\n\nToday, we'll work with sleep study data available in the `lme4` package. This study looks at how sleep deprivation affects reaction time.\n\n* Also load in our other usual packages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(brms)\ndata(\"sleepstudy\", package = \"lme4\")\n```\n:::\n\n## Example Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleepstudy %>% glimpse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` nowrap-code\nRows: 180\nColumns: 3\n$ Reaction <dbl> 249.5600, 258.7047, 250.8006, 321.4398, 356.8519, 414.6901, 3…\n$ Days     <dbl> 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0…\n$ Subject  <fct> 308, 308, 308, 308, 308, 308, 308, 308, 308, 308, 309, 309, 3…\n```\n\n\n:::\n:::\n\n\n* `Reaction`: average reaction time in milliseconds\n\n* `Days`: days of the study: days 0 and 1 are training, 2 is baseline, and sleep deprivation begins on day 3\n\n* `Subject`: indexes different individuals\n\nWe only want to study the effects of sleep deprivation, so we exclude days 0 and 1 and rescale so that `Days` indicates the number of sleep-deprived days:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleepstudy <- sleepstudy %>% filter(Days >= 2) %>% mutate(Days = Days - 2)\n```\n:::\n\n\n## Example Data\n\nWe have data for 8 days each of 18 subjects. Notice that reaction times range from 203.0 ms to 466.4 ms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(sleepstudy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Reaction          Days         Subject  \n Min.   :203.0   Min.   :0.00   308    : 8  \n 1st Qu.:265.2   1st Qu.:1.75   309    : 8  \n Median :303.2   Median :3.50   310    : 8  \n Mean   :308.0   Mean   :3.50   330    : 8  \n 3rd Qu.:347.7   3rd Qu.:5.25   331    : 8  \n Max.   :466.4   Max.   :7.00   332    : 8  \n                                (Other):96  \n```\n\n\n:::\n:::\n\n\n\n\n## Review: Varying Intercepts\n\nWe want to predict reaction times ($R$) from the number of days ($D$) of sleep deprivation.\n\n* To account for individual differences in reaction times, we will specify a random intercept associated with subjects.\n\n\\begin{align*}\nR & \\sim N(\\mu_i, \\sigma) \\\\\n\\mu & = a_i + bD_i \\\\\na_i & \\sim N(\\bar{a}, \\sigma_a) \\\\\nb & \\sim ??? \\\\\n\\bar{a} & \\sim ??? \\\\\n\\sigma_a & \\sim ??? \\\\\n\\sigma & \\sim ???\n\\end{align*}\n\nNow we need to specify priors for $b$, $\\bar{a}$, $\\sigma_a$, and $\\sigma$.\n\n## Prior Predictive Simulation: Varying Intercepts\n\nRemember that reaction times range from 203.0 to 466.4 on days 0-7.\n\n* $\\bar{a}$ is the average reaction time on day 0 (no sleep deprivation), so may be quicker than average\n\n    * Try $N(250, 20)$\n\n* $b$ is the predicted increase in reaction time for each additional day of sleep deprivation, likely positive\n\n    * Try $N(20, 10)$\n    \n* $\\sigma_a$ is the standard deviation of individual reaction times\n    \n    * Try $Exponential(.05)$: average 20 ms of individual differences\n    \n* $\\sigma$ is the standard deviation of residuals\n\n    * Try $Exponential(.1)$: hopefully our predictions are less variable than our subjects!\n\n## Prior Predictive Simulation: Varying Intercepts\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_prior(Reaction ~ Days + (1 | Subject), sleepstudy,\n          family = gaussian(link = \"identity\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` nowrap-code\n                     prior     class      coef   group resp dpar nlpar lb ub\n                    (flat)         b                                        \n                    (flat)         b      Days                              \n student_t(3, 303.2, 65.5) Intercept                                        \n     student_t(3, 0, 65.5)        sd                                    0   \n     student_t(3, 0, 65.5)        sd           Subject                  0   \n     student_t(3, 0, 65.5)        sd Intercept Subject                  0   \n     student_t(3, 0, 65.5)     sigma                                    0   \n tag       source\n          default\n     (vectorized)\n          default\n          default\n     (vectorized)\n     (vectorized)\n          default\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvi_pps <- brm(Reaction ~ Days + (1 | Subject), sleepstudy,\n              family = gaussian(link = \"identity\"),\n              prior = prior(\"normal(20, 10)\", class = \"b\") + \n                      prior(\"normal(250, 20)\", class = \"Intercept\") + \n                      prior(\"exponential(.05)\", class = \"sd\") + \n                      prior(\"exponential(.1)\", class = \"sigma\"),\n              sample_prior = \"only\")\n```\n:::\n\n\n## Prior Predictive Simulation: Varying Intercepts\n\n::: {.panel-tabset}\n\n## Predict Mean Line\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_effects(vi_pps, method = \"posterior_linpred\", \n                    spaghetti = TRUE, ndraws = 100)\n```\n\n::: {.cell-output-display}\n![](Multilevel_Models_II_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n## Predict Individual Variability\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_effects(vi_pps, method = \"posterior_predict\")\n```\n\n::: {.cell-output-display}\n![](Multilevel_Models_II_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n## Conclusion \n\nI think that predictions are a little bit lower than I would like. To adjust, I will increase my prior on the intercept $\\bar{a}$ to $N(280, 20)$. \n\n:::\n\n\n\n## Varying Intercepts\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvi_mod <- brm(Reaction ~ Days + (1 | Subject), sleepstudy,\n              family = gaussian(link = \"identity\"),\n              prior = prior(\"normal(20, 10)\", class = \"b\") + \n                      prior(\"normal(280, 20)\", class = \"Intercept\") + \n                      prior(\"exponential(.05)\", class = \"sd\") + \n                      prior(\"exponential(.1)\", class = \"sigma\"))\n```\n:::\n\n\n## Varying Intercepts\n\nAs a class, let's interpret (a) model convergence, (b) the interpretation of each parameter. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(vi_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` nowrap-code\n Family: gaussian \n  Links: mu = identity \nFormula: Reaction ~ Days + (1 | Subject) \n   Data: sleepstudy (Number of observations: 144) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nMultilevel Hyperparameters:\n~Subject (Number of levels: 18) \n              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsd(Intercept)    42.03      7.66    29.62    59.49 1.00      799     1183\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept   261.63     10.25   240.50   280.96 1.00      816     1227\nDays         11.56      1.11     9.31    13.72 1.00     5027     2966\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma    30.15      1.92    26.70    34.21 1.00     3423     2885\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n\n## Varying Intercepts\n\nWe can plot the cluster-specific slopes by setting `re_formula = NULL`. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(conditional_effects(vi_mod, method = \"posterior_predict\",\n                         re_formula = NULL,\n                         conditions = make_conditions(vi_mod, \"Subject\")),\n     points = TRUE)\n```\n:::\n\n\nThe plot is shown on the next slide so that we can see it better.\n\n## Varying Intercepts\n\nNotice that all slopes are parallel to each other but that the intercepts are adjusted to the individual.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Multilevel_Models_II_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n\n## Varying Slopes\n\nWhat if we wanted not only the **intercept** but the **slope** to vary across subjects? \n  \n  \n  \n  \\begin{align*}\nR & \\sim N(\\mu_i, \\sigma) \\\\\n\\mu & = a_i + b_iD_i \\\\\na_i & \\sim N(\\bar{a}, \\sigma_a) \\\\\nb_i & \\sim N(\\bar{b}, \\sigma_b) \\\\\n  \\begin{bmatrix}a_i \\\\ b_i\\end{bmatrix} & \\sim MVN\\left(\\begin{bmatrix} \\bar{a} \\\\ \\bar{b} \\end{bmatrix},\\pmb{S}\\right) \\\\\n  \\bar{a} & \\sim ??? \\\\\n  \\bar{b} & \\sim ??? \\\\\n  \\pmb{S} & \\sim ??? \\\\\n  \\end{align*}\n\n\nThrough the Cholesky decomposition, the covariance matrix $\\pmb{S}$ can be used such that we need to specify priors on $\\sigma_a$, $\\sigma_b$, and $r_{ab}$.\n\n## Varying Slopes\n\nWe can use the same priors as before on $\\bar{a}$,  $\\sigma_a$, $\\sigma$\n  \n  * We can use the same prior on $\\bar{b}$ as we previously used on $b$\n  \n  * Need a prior on $\\sigma_b$, the standard deviation of slopes: try $Exponential(.1)$\n  \n  * Need a prior on $r_{ab}$, the correlation between varying slopes and intercepts: try $LKJ(1)$\n  \n  \n  \n## Prior Predictive Simulation: Varying Slopes\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nget_prior(Reaction ~ Days + (Days | Subject), sleepstudy,\n          family = gaussian(link = \"identity\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` nowrap-code\n                     prior     class      coef   group resp dpar nlpar lb ub\n                    (flat)         b                                        \n                    (flat)         b      Days                              \n                    lkj(1)       cor                                        \n                    lkj(1)       cor           Subject                      \n student_t(3, 303.2, 65.5) Intercept                                        \n     student_t(3, 0, 65.5)        sd                                    0   \n     student_t(3, 0, 65.5)        sd           Subject                  0   \n     student_t(3, 0, 65.5)        sd      Days Subject                  0   \n     student_t(3, 0, 65.5)        sd Intercept Subject                  0   \n     student_t(3, 0, 65.5)     sigma                                    0   \n tag       source\n          default\n     (vectorized)\n          default\n     (vectorized)\n          default\n          default\n     (vectorized)\n     (vectorized)\n     (vectorized)\n          default\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvs_pps <- brm(Reaction ~ Days + (Days | Subject), sleepstudy,\n              family = gaussian(link = \"identity\"),\n              prior = prior(\"normal(20, 10)\", class = \"b\") + \n                prior(\"normal(280, 20)\", class = \"Intercept\") + \n                prior(\"exponential(.05)\", class = \"sd\", coef = \"Intercept\", group = \"Subject\") + \n                prior(\"exponential(.1)\", class = \"sd\", coef = \"Days\", group = \"Subject\") + \n                prior(\"exponential(.1)\", class = \"sigma\") + \n                prior(\"lkj(1)\", class = \"cor\"),\n              sample_prior = \"only\")\n```\n:::\n\n\n\n## Prior Predictive Simulation: Varying Slopes\n\n::: {.panel-tabset}\n\n## Predict Mean Line\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_effects(vs_pps, method = \"posterior_linpred\", \n                    spaghetti = TRUE, ndraws = 100)\n```\n\n::: {.cell-output-display}\n![](Multilevel_Models_II_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n## Predict Individual Variability\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_effects(vs_pps, method = \"posterior_predict\")\n```\n\n::: {.cell-output-display}\n![](Multilevel_Models_II_files/figure-revealjs/unnamed-chunk-16-1.png){width=960}\n:::\n:::\n\n\n## Conclusion \n\nThese are quite similar to the varying slope predictions. This should make some sense. The major change that we made was to allow indiviudals to have their own slopes rather than a big change in what the slope actually would be.\n\n:::\n  \n  \n  \n## Varying Slopes\n  \n\n::: {.cell}\n\n```{.r .cell-code}\nvs_mod <- brm(Reaction ~ Days + (Days | Subject), sleepstudy,\n              family = gaussian(link = \"identity\"),\n              prior = prior(\"normal(20, 10)\", class = \"b\") + \n                prior(\"normal(280, 20)\", class = \"Intercept\") + \n                prior(\"exponential(.05)\", class = \"sd\", coef = \"Intercept\", group = \"Subject\") + \n                prior(\"exponential(.1)\", class = \"sd\", coef = \"Days\", group = \"Subject\") + \n                prior(\"exponential(.1)\", class = \"sigma\") + \n                prior(\"lkj(1)\", class = \"cor\"))\n```\n:::\n\n\n## Varying Slopes\n\nAgain, let's interpret (a) model convergence, (b) the interpretation of each parameter. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(vs_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n``` nowrap-code\n Family: gaussian \n  Links: mu = identity \nFormula: Reaction ~ Days + (Days | Subject) \n   Data: sleepstudy (Number of observations: 144) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nMultilevel Hyperparameters:\n~Subject (Number of levels: 18) \n                    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsd(Intercept)          31.50      7.19    19.60    47.69 1.00     2019     2805\nsd(Days)                7.18      1.75     4.30    11.09 1.00     1439     2039\ncor(Intercept,Days)     0.21      0.31    -0.38     0.81 1.00     1245     1118\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept   264.18      7.91   247.89   279.31 1.00     1783     2592\nDays         11.09      1.89     7.24    14.98 1.00     1963     2167\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma    25.75      1.81    22.50    29.68 1.00     2926     2924\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n\n## Varying Slopes\n\n\nAgain this figure is shown on the next slide for clarity.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(conditional_effects(vs_mod, method = \"posterior_predict\",\n                         re_formula = NULL,\n                         conditions = make_conditions(vs_mod, \"Subject\")),\n                         points = TRUE)\n```\n:::\n\n\n\n## Varying Slopes\n\nWhat do you notice about the individual slopes?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Multilevel_Models_II_files/figure-revealjs/unnamed-chunk-20-1.png){width=960}\n:::\n:::\n\n\n\n## Activity\n\nIn this lab, we treated `Day` as a continuous variable, but there may be nonlinear or inconsistent effects of time. Using the techniques we learned about in the 2nd GLM lecture/lab, specify `Days` as an ordered categorical variable. We will now specify varying slopes on that ordered categorical variable.\n\n1. Conduct prior predictive simulation to select appropriate priors. \n\n2. Fit the model and evaluate convergence.\n\n3. Plot your results. Do you find that any particular day leads to particularly high increases in reaction time? Do reaction times \"level out\" after a certain number of deprivation days?\n\n4. Compare the fit of this model to the two models that we fit during lab, paying attention to any warnings that you find. Interpret the fit results.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}